### ISSUE TITLE
Cannot download data

### ISSUE THREAD

**Issue by skaae** [fyu/lsun#1]
When i run
```
python download.py
```

I get the error

```
Traceback (most recent call last):
  File "download.py", line 62, in <module>
    main()
  File "download.py", line 43, in main
    categories = list_categories(args.tag)
  File "download.py", line 20, in list_categories
    return json.loads(f.read())
  File "/Users/sorensonderby/anaconda/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Users/sorensonderby/anaconda/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/sorensonderby/anaconda/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

How do i solve this?

**Comment by fyu** [comment]
The storage server distributing the data is suffering some problem now. We are working to fix it.

**Comment by skaae** [comment]
ok. Thanks for the reply. Do you know how long it'll take approximately?

**Comment by skaae** [comment]
Whats the status?

**Comment by fyu** [comment]
The downloading is fixed. Sorry for the delay.
