### ISSUE TITLE
Failed to export Image

### ISSUE THREAD

**Issue by stm233** [fyu/lsun#22]
In my folder: bedroom_val, there are data.mdb and lock.mdb.

Then I use 

export_images('./bedroom_val', './data',True)

result:

```
Traceback (most recent call last):
  File "/Users/pegasus/Downloads/lsun-master/data.py", line 90, in <module>
    export_images('./bedroom_val', './data',True)
  File "/Users/pegasus/Downloads/lsun-master/data.py", line 48, in export_images
    image_out_path = join(image_out_dir, key + '.webp')
TypeError: can't concat str to bytes
```

Then i added  **_key.decode()_**  where
`image_out_path = join(image_out_dir, key.decode() + '.webp')`

However, there still has an error:

```
Traceback (most recent call last):
  File "/Users/pegasus/Downloads/lsun-master/data.py", line 90, in <module>
    export_images('./bedroom_val', './data',True)
  File "/Users/pegasus/Downloads/lsun-master/data.py", line 50, in export_images
    fp.write(val)
TypeError: write() argument must be str, not bytes
```
I don't know how to fix this problem where
```
            with open(image_out_path, 'w') as fp:
                fp.write(val)
```

**Comment by Richard-An** [comment]
same problem, waiting for the solution

**Comment by tlvu2697** [comment]
The output file needs to be written in binary mode. Try changing line 48 from
```
with open(image_out_path, 'w') as fp:
```
to
```
with open(image_out_path, 'wb') as fp:
```
Hope it helps you.

**Comment by i-chaochen** [comment]
@tlvu2697 do you know how to convert it to jpg?

**Comment by aviadpinis** [comment]
Show in https://github.com/fyu/lsun/issues/11#issuecomment-567390245.

**Comment by Tenoke** [comment]
Fixed in this [PR](https://github.com/fyu/lsun/pull/29).
